CREATE DATABASE hotels;
GRANT ALL PRIVILEGES ON DATABASE payment TO program;

CREATE DATABASE payments;
GRANT ALL PRIVILEGES ON DATABASE payment TO program;

CREATE DATABASE reservations;
GRANT ALL PRIVILEGES ON DATABASE reservation TO program;

CREATE DATABASE loyalties;
GRANT ALL PRIVILEGES ON DATABASE loyalty TO program;