name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      # TODO build and run unit tests

      - name: Build images
        timeout-minutes: 10
        run: docker compose build

      - name: Run containers
        timeout-minutes: 5
        run: |
          docker compose up -d
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050

  tests:
    name: Run xUnit tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: dotnet test gateway/gateway.sln --no-build --configuration Release

      - name: API tests
        uses: matt-ball/newman-action@master
        with:
          # TODO insert your variant
          collection: v2/postman/collection.json
          environment: v2/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v
